# Generated by Django 2.0.3 on 2018-06-06 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180601_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 3, 13, 38, 907842, tzinfo=utc)),
        ),
    ]
