# Generated by Django 2.0.3 on 2018-06-06 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20180606_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 12, 29, 58, 458679, tzinfo=utc)),
        ),
    ]
