# Generated by Django 2.0.3 on 2018-06-06 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20180606_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 21, 47, 52, 219100, tzinfo=utc)),
        ),
    ]
